music_directory "/Users/sourya4/pro/youtube_download/music"
playlist_directory "~/.mpd/playlists"
db_file "~/.mpd/database"
log_file "~/.mpd/log"
pid_file "~/.mpd/pid"
state_file "~/.mpd/state"
sticker_file "~/.mpd/sticker.sql"

bind_to_address "127.0.0.1"
port "6600"
auto_update "yes"
restore_paused "yes"

audio_output {
    type "osx"
    name "CoreAudio"
    mixer_type "software"
}

audio_output {
    type "fifo"
    name "Visualizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}
